// Generated by @revolist/stencil-dash-output-target. Do not edit.
import React, {
  forwardRef,
  useImperativeHandle,
  useLayoutEffect,
  useRef,
} from 'react';
import PropTypes from 'prop-types';
import {
  applyElementProperties,
  bindEventListeners,
  compactAfterEditDetail,
  createEventEnvelope,
  createSourceSyncToken,
  normalizeEventNames,
} from '@revolist/stencil-dash-output-target/runtime';
import { defineCustomElement as defineRevoGridCustomElement } from "../define-custom-elements.js";

if (
  typeof customElements !== 'undefined'
) {
  defineRevoGridCustomElement();
}

const GRID_PROPERTY_NAMES = Object.freeze(["accessible","additionalData","applyOnClose","autoSizeColumn","canDrag","canFocus","canMoveColumns","colSize","columns","columnTypes","disableVirtualX","disableVirtualY","exporting","filter","frameSize","grouping","hideAttribution","noHorizontalScrollTransfer","pinnedBottomSource","pinnedTopSource","range","readonly","resize","rowClass","rowDefinitions","rowHeaders","rowSize","rtl","sorting","source","stretch","theme","trimmedRows","useClipboard","virtualX"]);
const EVENT_MAPPINGS = Object.freeze({
  "aftercolumnresize": "aftercolumnresize",
  "afteredit": "afteredit",
  "afterfocus": "afterfocus",
  "aftersortingapply": "aftersortingapply",
  "beforefilterapply": "beforefilterapply",
  "headerclick": "headerclick",
  "roworderchanged": "roworderchanged"
});

/**
 * Revogrid - High-performance, customizable grid library for managing large datasets. ### Events guide For a comprehensive events guide, check the [Events API Page](/guide/api/events). All events propagate to the root level of the grid. [Dependency tree](#Dependencies). ### Type definitions Read [type definition file](https://github.com/revolist/revogrid/blob/master/src/interfaces.d.ts) for the full interface information. All complex property types such as `ColumnRegular`, `ColumnProp`, `ColumnDataSchemaModel` can be found there. ### HTMLRevoGridElement
 */
const RevoGrid = forwardRef(function RevoGrid(props, forwardedRef) {
  const hostRef = useRef(null);
  const elementRef = useRef(null);
  const previousPropsRef = useRef({});
  const pendingSourceSyncRef = useRef(null);
  const sequenceRef = useRef(0);

  if (!elementRef.current && typeof document !== 'undefined') {
    const element = document.createElement("revo-grid");
    element.style.display = 'block';
    element.style.width = '100%';
    element.style.height = '100%';
    applyElementProperties(
      element,
      GRID_PROPERTY_NAMES,
      props,
      previousPropsRef.current,
    );
    elementRef.current = element;
  }

  useImperativeHandle(forwardedRef, () => elementRef.current, []);

  useLayoutEffect(() => {
    const element = elementRef.current;
    if (!element) {
      return;
    }
    const result = applyElementProperties(
      element,
      GRID_PROPERTY_NAMES,
      props,
      previousPropsRef.current,
      pendingSourceSyncRef.current,
    );
    if (result.sourceSyncConsumed) {
      pendingSourceSyncRef.current = null;
    }
  });

  useLayoutEffect(() => {
    const element = elementRef.current;
    if (!element) {
      return undefined;
    }
    const listeners = {};
    for (const [eventName, dashProp] of Object.entries(EVENT_MAPPINGS)) {
      listeners[eventName] = event => {
        sequenceRef.current += 1;
        const detail =
          eventName === 'afteredit'
            ? compactAfterEditDetail(event.detail)
            : event.detail;
        const envelope = createEventEnvelope(
          eventName,
          detail,
          sequenceRef.current,
        );
        const updates = { [dashProp]: envelope };
        if (
          eventName === 'afteredit' &&
          props.syncSourceOnEdit &&
          'source' in element
        ) {
          const token = createSourceSyncToken(element.source);
          pendingSourceSyncRef.current = token;
          updates.source = token.value;
        }
        if (props.setProps) {
          props.setProps(updates);
        }
      };
    }
    const genericListeners = {};
    for (const eventName of normalizeEventNames(props.eventListeners)) {
      if (eventName in EVENT_MAPPINGS) {
        continue;
      }
      genericListeners[eventName] = event => {
        sequenceRef.current += 1;
        if (props.setProps) {
          props.setProps({
            eventData: createEventEnvelope(
              eventName,
              event.detail,
              sequenceRef.current,
            ),
          });
        }
      };
    }
    const cleanupDedicated = bindEventListeners(element, listeners);
    const cleanupGeneric = bindEventListeners(element, genericListeners);
    return () => {
      cleanupDedicated();
      cleanupGeneric();
    };
  }, [
    props.eventListeners,
    props.setProps,
    props.syncSourceOnEdit,
  ]);

  useLayoutEffect(() => {
    const host = hostRef.current;
    const element = elementRef.current;
    if (!host || !element) {
      return undefined;
    }
    host.appendChild(element);
    return () => element.remove();
  }, []);

  return React.createElement('div', {
    ref: hostRef,
    id: props.id,
    className: props.className,
    style: {
      display: 'block',
      width: '100%',
      ...props.style,
    },
  });
});

RevoGrid.displayName = "RevoGrid";

RevoGrid.propTypes = {
  /** Dash component identifier. */
  id: PropTypes.string,
  /** CSS class applied to the RevoGrid component host. */
  className: PropTypes.string,
  /** Inline style applied to the RevoGrid component host. */
  style: PropTypes.object,
  /** Enable accessibility. If disabled, the grid will not be accessible. */
  accessible: PropTypes.bool,
  /** Additional data to be passed to plugins, renders or editors. For example if you need to pass Vue component instance. */
  additionalData: PropTypes.any,
  /** Apply changes in editor when closed except 'Escape' cases. If custom editor in use method getValue required. Check interfaces.d.ts `EditorBase` for more info. */
  applyOnClose: PropTypes.bool,
  /** Autosize config. Enables columns autoSize. For more details check `autoSizeColumn` plugin. By default disabled, hence operation is not performance efficient. `true` to enable with default params (double header separator click for autosize). Or define config. See `AutoSizeColumnConfig` for more details. */
  autoSizeColumn: PropTypes.bool,
  /** Disable native drag&drop plugin. */
  canDrag: PropTypes.bool,
  /** When true cell focus appear. */
  canFocus: PropTypes.bool,
  /** Enable column move plugin. */
  canMoveColumns: PropTypes.bool,
  /** Indicates default column size. */
  colSize: PropTypes.number,
  /** Columns - defines an array of grid columns. Can be column or grouped column. */
  columns: PropTypes.array,
  /** Column Types Format. Every type represent multiple column properties. Types will be merged but can be replaced with column properties. Types were made as separate objects to be reusable per multiple columns. */
  columnTypes: PropTypes.object,
  /** Disable lazy rendering mode for the `X axis`. Use when not many columns present and you don't need rerenader cells during scroll. Can be used for initial rendering performance improvement. */
  disableVirtualX: PropTypes.bool,
  /** Disable lazy rendering mode for the `Y axis`. Use when not many rows present and you don't need rerenader cells during scroll. Can be used for initial rendering performance improvement. */
  disableVirtualY: PropTypes.bool,
  /** Enable export plugin. */
  exporting: PropTypes.bool,
  /** Enables filter plugin. Can be boolean. Or can be filter collection See `FilterCollection` for more info. */
  filter: PropTypes.bool,
  /** Defines how many rows/columns should be rendered outside visible area. */
  frameSize: PropTypes.number,
  /** Group rows based on this property. Define properties to be groped by grouping plugin See `GroupingOptions`. */
  grouping: PropTypes.object,
  /** Please only hide the attribution if you are subscribed to Pro version */
  hideAttribution: PropTypes.bool,
  /** Prevents horizontal scroll state from being mirrored across viewport sections. */
  noHorizontalScrollTransfer: PropTypes.bool,
  /** Pinned bottom Source: {[T in ColumnProp]: any} - defines pinned bottom rows data source. */
  pinnedBottomSource: PropTypes.array,
  /** Pinned top Source: {[T in ColumnProp]: any} - defines pinned top rows data source. */
  pinnedTopSource: PropTypes.array,
  /** When true, user can select a cell range. Required for range-based clipboard fill. */
  range: PropTypes.bool,
  /** When true, grid in read only mode. */
  readonly: PropTypes.bool,
  /** When true, columns are resizable. */
  resize: PropTypes.bool,
  /** Row class property mapping. Map custom classes to rows from row object data. Define this property in rgRow object and this will be mapped as rgRow class. */
  rowClass: PropTypes.string,
  /** Custom row properies to be applied. See `RowDefinition` for more info. */
  rowDefinitions: PropTypes.array,
  /** Excel like functionality. Show row numbers. Also can be used for custom row header render if object provided. */
  rowHeaders: PropTypes.bool,
  /** Indicates default rgRow size. By default 0, means theme package size will be applied Alternatively you can use `rowSize` to reset viewport */
  rowSize: PropTypes.number,
  /** Enable right-to-left (RTL) mode. When enabled, columns will be displayed from right to left. */
  rtl: PropTypes.bool,
  /** Alternative way to set sorting. `{columns: [{prop: 'name', order: 'asc'}]}` Use SortingPlugin to get current sorting state */
  sorting: PropTypes.object,
  /** Source - defines main data source. Can be an Object or 2 dimensional array([][]); Keys/indexes referenced from columns Prop. */
  source: PropTypes.array,
  /** Stretch strategy for columns by `StretchColumn` plugin. For example if there are more space on the right last column size would be increased. */
  stretch: PropTypes.oneOfType([PropTypes.bool, PropTypes.string]),
  /** Theme name. */
  theme: PropTypes.string,
  /** Trimmed rows. Functionality which allows to hide rows from main data set. `trimmedRows` are physical `rgRow` indexes to hide. */
  trimmedRows: PropTypes.oneOfType([PropTypes.bool, PropTypes.number]),
  /** When true enable clipboard. Can be boolean or clipboard config. */
  useClipboard: PropTypes.bool,
  /** Column dimensions that use X axis virtual rendering. Defaults to regular columns only to preserve pinned column behavior. Set to `['rgCol', 'colPinStart', 'colPinEnd']` to virtualize all column areas. */
  virtualX: PropTypes.array,
  /** Emitted after column resizing. Useful for retrieving the resized columns. Contains a JSON-safe event envelope. */
  aftercolumnresize: PropTypes.object,
  /** After data applied or range changed. Contains a JSON-safe event envelope. */
  afteredit: PropTypes.object,
  /** After focus render finished. Can be used to access a focus element through `event.target`. This is just a duplicate of `afterfocus` from `revogr-focus.tsx`. Contains a JSON-safe event envelope. */
  afterfocus: PropTypes.object,
  /** By `SortingPlugin` <br>Triggered after sorting has been applied and completed. <br>Provides final sorting state and sorting column metadata when available. Contains a JSON-safe event envelope. */
  aftersortingapply: PropTypes.object,
  /** Emitted before applying a filter to the data source. Use e.preventDefault() to prevent cell focus change. Modify if you need to change filters. Contains a JSON-safe event envelope. */
  beforefilterapply: PropTypes.object,
  /** On header click. Contains a JSON-safe event envelope. */
  headerclick: PropTypes.object,
  /** Before the order of `rgRow` is applied. To prevent the default behavior of changing the order of `rgRow`, you can call `e.preventDefault()`. Contains a JSON-safe event envelope. */
  roworderchanged: PropTypes.object,
  /** Additional RevoGrid event names to publish through eventData. */
  eventListeners: PropTypes.arrayOf(PropTypes.string),
  /** Latest JSON-safe event envelope from eventListeners. */
  eventData: PropTypes.object,
  /** When true, afteredit also updates the complete Dash source property. */
  syncSourceOnEdit: PropTypes.bool,
  /** Dash callback used to report property changes. */
  setProps: PropTypes.func,
};

RevoGrid.defaultProps = {
  eventListeners: [],
  syncSourceOnEdit: false,
};

export default RevoGrid;
