// Generated by @revolist/stencil-dash-output-target. Do not edit.
import React, {
  forwardRef,
  useImperativeHandle,
  useLayoutEffect,
  useRef,
} from 'react';
import PropTypes from 'prop-types';
import {
  applyElementProperties,
  bindEventListeners,
  compactAfterEditDetail,
  createEventEnvelope,
  createSourceSyncToken,
  normalizeEventNames,
} from '@revolist/stencil-dash-output-target/runtime';
import { defineCustomElement as defineRevoGridCustomElement } from "../define-custom-elements.js";

if (
  typeof customElements !== 'undefined'
) {
  defineRevoGridCustomElement();
}

const GRID_PROPERTY_NAMES = Object.freeze(["accessible","additionalData","applyOnClose","autoSizeColumn","canDrag","canFocus","canMoveColumns","colSize","columns","columnTypes","disableVirtualX","disableVirtualY","exporting","filter","frameSize","grouping","hideAttribution","noHorizontalScrollTransfer","pinnedBottomSource","pinnedTopSource","range","readonly","resize","resizeRow","rowClass","rowDefinitions","rowHeaders","rowSize","rtl","sorting","source","stretch","theme","themeDefinitions","trimmedRows","useClipboard","virtualX"]);
const EVENT_MAPPINGS = Object.freeze({
  "additionaldatachanged": "additionaldatachanged",
  "afteranysource": "afteranysource",
  "aftercolumnresize": "aftercolumnresize",
  "aftercolumnsset": "aftercolumnsset",
  "afteredit": "afteredit",
  "afterfocus": "afterfocus",
  "aftergridinit": "aftergridinit",
  "aftergridrender": "aftergridrender",
  "aftersortingapply": "aftersortingapply",
  "aftersourceset": "aftersourceset",
  "afterthemechanged": "afterthemechanged",
  "aftertrimmed": "aftertrimmed",
  "beforeanysource": "beforeanysource",
  "beforeautofill": "beforeautofill",
  "beforecellfocus": "beforecellfocus",
  "beforecolumnapplied": "beforecolumnapplied",
  "beforecolumnsgather": "beforecolumnsgather",
  "beforecolumnsset": "beforecolumnsset",
  "beforeedit": "beforeedit",
  "beforeeditstart": "beforeeditstart",
  "beforeexport": "beforeexport",
  "beforefilterapply": "beforefilterapply",
  "beforefiltertrimmed": "beforefiltertrimmed",
  "beforefocuslost": "beforefocuslost",
  "beforegridrender": "beforegridrender",
  "beforerange": "beforerange",
  "beforerangeedit": "beforerangeedit",
  "beforerowdefinition": "beforerowdefinition",
  "beforesorting": "beforesorting",
  "beforesortingapply": "beforesortingapply",
  "beforesourceset": "beforesourceset",
  "beforesourcesortingapply": "beforesourcesortingapply",
  "beforetrimmed": "beforetrimmed",
  "contentsizechanged": "contentsizechanged",
  "created": "created",
  "filterconfigchanged": "filterconfigchanged",
  "headerclick": "headerclick",
  "rowdragstart": "rowdragstart",
  "rowheaderschanged": "rowheaderschanged",
  "roworderchanged": "roworderchanged",
  "sortingconfigchanged": "sortingconfigchanged",
  "viewportscroll": "viewportscroll"
});
const DEFAULT_EVENT_NAMES = Object.freeze(["aftercolumnresize","afteredit","afterfocus","aftersortingapply","beforefilterapply","headerclick","roworderchanged"]);

/**
 * Revogrid - High-performance, customizable grid library for managing large datasets. ### Events guide For a comprehensive events guide, check the [Events API Page](/guide/api/events). All events propagate to the root level of the grid. [Dependency tree](#Dependencies). ### Type definitions Read [type definition file](https://github.com/revolist/revogrid/blob/master/src/interfaces.d.ts) for the full interface information. All complex property types such as `ColumnRegular`, `ColumnProp`, `ColumnDataSchemaModel` can be found there. ### HTMLRevoGridElement
 */
const RevoGrid = forwardRef(function RevoGrid(props, forwardedRef) {
  const hostRef = useRef(null);
  const elementRef = useRef(null);
  const previousPropsRef = useRef({});
  const pendingSourceSyncRef = useRef(null);
  const sequenceRef = useRef(0);

  if (!elementRef.current && typeof document !== 'undefined') {
    const element = document.createElement("revo-grid");
    element.style.display = 'block';
    element.style.width = '100%';
    element.style.height = '100%';
    applyElementProperties(
      element,
      GRID_PROPERTY_NAMES,
      props,
      previousPropsRef.current,
    );
    elementRef.current = element;
  }

  useImperativeHandle(forwardedRef, () => elementRef.current, []);

  useLayoutEffect(() => {
    const element = elementRef.current;
    if (!element) {
      return;
    }
    const result = applyElementProperties(
      element,
      GRID_PROPERTY_NAMES,
      props,
      previousPropsRef.current,
      pendingSourceSyncRef.current,
    );
    if (result.sourceSyncConsumed) {
      pendingSourceSyncRef.current = null;
    }
  });

  useLayoutEffect(() => {
    const element = elementRef.current;
    if (!element) {
      return undefined;
    }
    const selectedEventNames = new Set([
      ...DEFAULT_EVENT_NAMES,
      ...normalizeEventNames(props.eventListeners),
    ]);
    const dedicatedListeners = {};
    const genericListeners = {};
    for (const eventName of selectedEventNames) {
      const dashProp = Object.prototype.hasOwnProperty.call(
        EVENT_MAPPINGS,
        eventName,
      )
        ? EVENT_MAPPINGS[eventName]
        : undefined;
      if (!dashProp) {
        genericListeners[eventName] = event => {
          sequenceRef.current += 1;
          if (props.setProps) {
            props.setProps({
              eventData: createEventEnvelope(
                eventName,
                event.detail,
                sequenceRef.current,
              ),
            });
          }
        };
        continue;
      }
      dedicatedListeners[eventName] = event => {
        sequenceRef.current += 1;
        const detail =
          eventName === 'afteredit'
            ? compactAfterEditDetail(event.detail)
            : event.detail;
        const envelope = createEventEnvelope(
          eventName,
          detail,
          sequenceRef.current,
        );
        const updates = { [dashProp]: envelope };
        if (!DEFAULT_EVENT_NAMES.includes(eventName)) {
          updates.eventData = envelope;
        }
        if (
          eventName === 'afteredit' &&
          props.syncSourceOnEdit &&
          'source' in element
        ) {
          const token = createSourceSyncToken(element.source);
          pendingSourceSyncRef.current = token;
          updates.source = token.value;
        }
        if (props.setProps) {
          props.setProps(updates);
        }
      };
    }
    const cleanupDedicated = bindEventListeners(element, dedicatedListeners);
    const cleanupGeneric = bindEventListeners(element, genericListeners);
    return () => {
      cleanupDedicated();
      cleanupGeneric();
    };
  }, [
    props.eventListeners,
    props.setProps,
    props.syncSourceOnEdit,
  ]);

  useLayoutEffect(() => {
    const host = hostRef.current;
    const element = elementRef.current;
    if (!host || !element) {
      return undefined;
    }
    host.appendChild(element);
    return () => element.remove();
  }, []);

  return React.createElement('div', {
    ref: hostRef,
    id: props.id,
    className: props.className,
    style: {
      display: 'block',
      width: '100%',
      ...props.style,
    },
  });
});

RevoGrid.displayName = "RevoGrid";

RevoGrid.propTypes = {
  /** Dash component identifier. */
  id: PropTypes.string,
  /** CSS class applied to the RevoGrid component host. */
  className: PropTypes.string,
  /** Inline style applied to the RevoGrid component host. */
  style: PropTypes.object,
  /** Enable accessibility. If disabled, the grid will not be accessible. */
  accessible: PropTypes.bool,
  /** Additional data to be passed to plugins, renders or editors. For example if you need to pass Vue component instance. */
  additionalData: PropTypes.any,
  /** Apply changes in editor when closed except 'Escape' cases. If custom editor in use method getValue required. Check interfaces.d.ts `EditorBase` for more info. */
  applyOnClose: PropTypes.bool,
  /** Autosize config. Enables columns autoSize. For more details check `autoSizeColumn` plugin. By default disabled, hence operation is not performance efficient. `true` to enable with default params (double header separator click for autosize). Or define config. See `AutoSizeColumnConfig` for more details. */
  autoSizeColumn: PropTypes.bool,
  /** Disable native drag&drop plugin. */
  canDrag: PropTypes.bool,
  /** When true cell focus appear. */
  canFocus: PropTypes.bool,
  /** Enable column move plugin. */
  canMoveColumns: PropTypes.bool,
  /** Indicates default column size. */
  colSize: PropTypes.number,
  /** Columns - defines an array of grid columns. Can be column or grouped column. */
  columns: PropTypes.array,
  /** Column Types Format. Every type represent multiple column properties. Types will be merged but can be replaced with column properties. Types were made as separate objects to be reusable per multiple columns. */
  columnTypes: PropTypes.object,
  /** Disable lazy rendering mode for the `X axis`. Use when not many columns present and you don't need rerenader cells during scroll. Can be used for initial rendering performance improvement. */
  disableVirtualX: PropTypes.bool,
  /** Disable lazy rendering mode for the `Y axis`. Use when not many rows present and you don't need rerenader cells during scroll. Can be used for initial rendering performance improvement. */
  disableVirtualY: PropTypes.bool,
  /** Enable export plugin. */
  exporting: PropTypes.bool,
  /** Enables filter plugin. Enabled by default; set to `false` to opt out. Can be boolean. Or can be filter collection See `FilterCollection` for more info. */
  filter: PropTypes.bool,
  /** Defines how many rows/columns should be rendered outside visible area. */
  frameSize: PropTypes.number,
  /** Group rows based on this property. Define properties to be groped by grouping plugin See `GroupingOptions`. */
  grouping: PropTypes.object,
  /** Please only hide the attribution if you are subscribed to Pro version */
  hideAttribution: PropTypes.bool,
  /** Prevents horizontal scroll state from being mirrored across viewport sections. */
  noHorizontalScrollTransfer: PropTypes.bool,
  /** Pinned bottom Source: {[T in ColumnProp]: any} - defines pinned bottom rows data source. */
  pinnedBottomSource: PropTypes.array,
  /** Pinned top Source: {[T in ColumnProp]: any} - defines pinned top rows data source. */
  pinnedTopSource: PropTypes.array,
  /** When true, user can select a cell range. Required for range-based clipboard fill. */
  range: PropTypes.bool,
  /** When true, grid in read only mode. */
  readonly: PropTypes.bool,
  /** When true, columns are resizable. */
  resize: PropTypes.bool,
  /** Enables row resizing. Pass a configuration object to customize the height limits or enable resize edges across the full row. */
  resizeRow: PropTypes.bool,
  /** Row class property mapping. Map custom classes to rows from row object data. Define this property in rgRow object and this will be mapped as rgRow class. */
  rowClass: PropTypes.string,
  /** Custom row properies to be applied. See `RowDefinition` for more info. */
  rowDefinitions: PropTypes.array,
  /** Excel like functionality. Show row numbers. Also can be used for custom row header render if object provided. */
  rowHeaders: PropTypes.bool,
  /** Indicates default rgRow size. By default 0, means theme package size will be applied Alternatively you can use `rowSize` to reset viewport */
  rowSize: PropTypes.number,
  /** Enable right-to-left (RTL) mode. When enabled, columns will be displayed from right to left. */
  rtl: PropTypes.bool,
  /** Alternative way to set sorting. `{columns: [{prop: 'name', order: 'asc'}]}` Use SortingPlugin to get current sorting state */
  sorting: PropTypes.object,
  /** Source - defines main data source. Can be an Object or 2 dimensional array([][]); Keys/indexes referenced from columns Prop. */
  source: PropTypes.array,
  /** Stretch strategy for columns by `StretchColumn` plugin. For example if there are more space on the right last column size would be increased. */
  stretch: PropTypes.oneOfType([PropTypes.bool, PropTypes.string]),
  /** Theme name. */
  theme: PropTypes.string,
  /** Per-grid custom theme definitions. Assign as a JavaScript property; complex values cannot be serialized as HTML attributes. */
  themeDefinitions: PropTypes.array,
  /** Trimmed rows. Functionality which allows to hide rows from main data set. `trimmedRows` are physical `rgRow` indexes to hide. */
  trimmedRows: PropTypes.oneOfType([PropTypes.bool, PropTypes.number]),
  /** When true enable clipboard. Can be boolean or clipboard config. */
  useClipboard: PropTypes.bool,
  /** Column dimensions that use X axis virtual rendering. Defaults to regular columns only to preserve pinned column behavior. Set to `['rgCol', 'colPinStart', 'colPinEnd']` to virtualize all column areas. */
  virtualX: PropTypes.array,
  /** Emmited after the additional data is changed Contains a JSON-safe event envelope. */
  additionaldatachanged: PropTypes.object,
  /** Emitted after each source update, whether from the pinned or main viewport. Useful for tracking all changes originating from sources in both the pinned and main viewports. Contains a JSON-safe event envelope. */
  afteranysource: PropTypes.object,
  /** Emitted after column resizing. Useful for retrieving the resized columns. Contains a JSON-safe event envelope. */
  aftercolumnresize: PropTypes.object,
  /** Column updated Contains a JSON-safe event envelope. */
  aftercolumnsset: PropTypes.object,
  /** After data applied or range changed. Contains a JSON-safe event envelope. */
  afteredit: PropTypes.object,
  /** After focus render finished. Can be used to access a focus element through `event.target`. This is just a duplicate of `afterfocus` from `revogr-focus.tsx`. Contains a JSON-safe event envelope. */
  afterfocus: PropTypes.object,
  /** Emmited after the grid is initialized. Connected to the DOM. Contains a JSON-safe event envelope. */
  aftergridinit: PropTypes.object,
  /** Emmited after the grid is rendered. Contains a JSON-safe event envelope. */
  aftergridrender: PropTypes.object,
  /** By `SortingPlugin` <br>Triggered after sorting has been applied and completed. <br>Provides final sorting state and sorting column metadata when available. Contains a JSON-safe event envelope. */
  aftersortingapply: PropTypes.object,
  /** After main source/rows updated Contains a JSON-safe event envelope. */
  aftersourceset: PropTypes.object,
  /** Emmited after the theme is changed Contains a JSON-safe event envelope. */
  afterthemechanged: PropTypes.object,
  /** Emitted after trimmed values have been applied. Useful for notifying when trimming of values has taken place. Contains a JSON-safe event envelope. */
  aftertrimmed: PropTypes.object,
  /** Before data apply on any source type. Can be source from pinned and main viewport. You can override data source here Contains a JSON-safe event envelope. */
  beforeanysource: PropTypes.object,
  /** Before autofill is applied. To prevent the default behavior of applying the edit data, you can call `e.preventDefault()`. Contains a JSON-safe event envelope. */
  beforeautofill: PropTypes.object,
  /** Before the cell focus is changed. To prevent the default behavior of changing the cell focus, you can call `e.preventDefault()`. Contains a JSON-safe event envelope. */
  beforecellfocus: PropTypes.object,
  /** Emitted before a column update is applied, after the column set is gathered and the viewport is updated. Useful for performing actions or modifications before the final application of the column update. Contains a JSON-safe event envelope. */
  beforecolumnapplied: PropTypes.object,
  /** Emitted before user column definitions are gathered into the internal column collection. Listeners can replace `detail.columns` to rewrite the raw column set before RevoGrid normalizes it. Contains a JSON-safe event envelope. */
  beforecolumnsgather: PropTypes.object,
  /** Emitted before a column update is applied. Listeners can use this event to perform any necessary actions or modifications before the column update is finalized. Contains a JSON-safe event envelope. */
  beforecolumnsset: PropTypes.object,
  /** Before the data is edited. To prevent the default behavior of editing data and use your own implementation, call `e.preventDefault()`. To override the edit result with your own value, set the `e.val` property to your desired value. Contains a JSON-safe event envelope. */
  beforeedit: PropTypes.object,
  /** Emitted before editing starts. Use e.preventDefault() to prevent the default edit behavior. Contains a JSON-safe event envelope. */
  beforeeditstart: PropTypes.object,
  /** Before export Use e.preventDefault() to prevent export Replace data in Event in case you want to modify it in export Contains a JSON-safe event envelope. */
  beforeexport: PropTypes.object,
  /** Emitted before applying a filter to the data source. Use e.preventDefault() to prevent cell focus change. Modify if you need to change filters. Contains a JSON-safe event envelope. */
  beforefilterapply: PropTypes.object,
  /** Emitted before applying a filter to the data source. Use e.preventDefault() to prevent the default behavior of trimming values and applying the filter. Modify the `collection` property if you want to change the filters. Modify the `itemsToFilter` property if you want to filter the indexes for trimming. Contains a JSON-safe event envelope. */
  beforefiltertrimmed: PropTypes.object,
  /** Before the grid focus is lost. To prevent the default behavior of changing the cell focus, you can call `e.preventDefault()`. Contains a JSON-safe event envelope. */
  beforefocuslost: PropTypes.object,
  /** Emmited before the grid is rendered. Contains a JSON-safe event envelope. */
  beforegridrender: PropTypes.object,
  /** Before autofill is applied. Runs before beforeautofill event. Use e.preventDefault() to prevent range. Contains a JSON-safe event envelope. */
  beforerange: PropTypes.object,
  /** Before applying range data, specifically when a range selection occurs. To customize the data and prevent the default edit data from being set, you can call `e.preventDefault()`. Contains a JSON-safe event envelope. */
  beforerangeedit: PropTypes.object,
  /** Emitted before the row definition is applied. Useful for modifying or preventing the default row definition behavior. Contains a JSON-safe event envelope. */
  beforerowdefinition: PropTypes.object,
  /** By `SortingPlugin` <br>Triggered immediately after header click. <br>First in sorting event sequence. Ff this event stops no other event called. <br>Use `e.preventDefault()` to prevent sorting. Contains a JSON-safe event envelope. */
  beforesorting: PropTypes.object,
  /** By `SortingPlugin` <br> After `beforesorting` <br>Triggered after column data updated with new sorting order. <br>Use `e.preventDefault()` to prevent sorting data change. Contains a JSON-safe event envelope. */
  beforesortingapply: PropTypes.object,
  /** Before main source/rows data apply. You can override data source here Contains a JSON-safe event envelope. */
  beforesourceset: PropTypes.object,
  /** By `SortingPlugin` <br>Same as `beforesorting` but triggered after `beforeanysource` (when source is changed). <br>Use `e.preventDefault()` to prevent sorting data change. Contains a JSON-safe event envelope. */
  beforesourcesortingapply: PropTypes.object,
  /** Emitted before trimming values. Use e.preventDefault() to prevent the default behavior of trimming values. Modify the `trimmed` property if you want to filter the indexes for trimming. Contains a JSON-safe event envelope. */
  beforetrimmed: PropTypes.object,
  /** New content size has been applied. The size excludes the header. Currently, the event responsible for applying the new content size does not provide the actual size. To retrieve the actual content size, you can utilize the `getContentSize` function after the event has been triggered. Contains a JSON-safe event envelope. */
  contentsizechanged: PropTypes.object,
  /** Emmited after grid created Contains a JSON-safe event envelope. */
  created: PropTypes.object,
  /** Emitted when the filter configuration is changed Contains a JSON-safe event envelope. */
  filterconfigchanged: PropTypes.object,
  /** On header click. Contains a JSON-safe event envelope. */
  headerclick: PropTypes.object,
  /** This event is triggered when the row order change is started. To prevent the default behavior of changing the row order, you can call `e.preventDefault()`. To change the item name at the start of the row order change, you can set `e.text` to the desired new name. Contains a JSON-safe event envelope. */
  rowdragstart: PropTypes.object,
  /** Emmited when the row headers are changed. Contains a JSON-safe event envelope. */
  rowheaderschanged: PropTypes.object,
  /** Before the order of `rgRow` is applied. To prevent the default behavior of changing the order of `rgRow`, you can call `e.preventDefault()`. Contains a JSON-safe event envelope. */
  roworderchanged: PropTypes.object,
  /** Emitted when the sorting configuration is changed SortingPlugin subsribed to this event Contains a JSON-safe event envelope. */
  sortingconfigchanged: PropTypes.object,
  /** Emitted when the viewport is scrolled. Useful for tracking viewport scrolling events. Contains a JSON-safe event envelope. */
  viewportscroll: PropTypes.object,
  /** Additional RevoGrid event names to publish through eventData. */
  eventListeners: PropTypes.arrayOf(PropTypes.string),
  /** Latest JSON-safe event envelope from eventListeners. */
  eventData: PropTypes.object,
  /** When true, afteredit also updates the complete Dash source property. */
  syncSourceOnEdit: PropTypes.bool,
  /** Dash callback used to report property changes. */
  setProps: PropTypes.func,
};

RevoGrid.defaultProps = {
  eventListeners: [],
  syncSourceOnEdit: false,
};

export default RevoGrid;
