// Generated by @revolist/stencil-dash-output-target. Do not edit.
import React, {
  forwardRef,
  useImperativeHandle,
  useLayoutEffect,
  useRef,
} from 'react';
import PropTypes from 'prop-types';
import {
  applyElementProperties,
  bindEventListeners,
  compactAfterEditDetail,
  createEventEnvelope,
  createSourceSyncToken,
  normalizeEventNames,
} from '@revolist/stencil-dash-output-target/runtime';
import { defineCustomElement as defineRevoGridCustomElement } from '../define-custom-elements.js';

if (
  typeof customElements !== 'undefined'
) {
  defineRevoGridCustomElement();
}

const GRID_PROPERTY_NAMES = Object.freeze([
  'accessible',
  'additionalData',
  'applyOnClose',
  'autoSizeColumn',
  'canDrag',
  'canFocus',
  'canMoveColumns',
  'colSize',
  'columnTypes',
  'columns',
  'disableVirtualX',
  'disableVirtualY',
  'exporting',
  'filter',
  'frameSize',
  'grouping',
  'hideAttribution',
  'noHorizontalScrollTransfer',
  'pinnedBottomSource',
  'pinnedTopSource',
  'range',
  'readonly',
  'resize',
  'rowClass',
  'rowDefinitions',
  'rowHeaders',
  'rowSize',
  'rtl',
  'sorting',
  'source',
  'stretch',
  'theme',
  'trimmedRows',
  'useClipboard',
  'virtualX',
]);
const EVENT_MAPPINGS = Object.freeze({
  aftercolumnresize: 'aftercolumnresize',
  afteredit: 'afteredit',
  afterfocus: 'afterfocus',
  aftersortingapply: 'aftersortingapply',
  beforefilterapply: 'beforefilterapply',
  headerclick: 'headerclick',
  roworderchanged: 'roworderchanged',
});

/**
 * High-performance virtual data grid exposed as a Plotly Dash component.
 */
const RevoGrid = forwardRef(function RevoGrid(props, forwardedRef) {
  const hostRef = useRef(null);
  const elementRef = useRef(null);
  const previousPropsRef = useRef({});
  const pendingSourceSyncRef = useRef(null);
  const sequenceRef = useRef(0);

  if (!elementRef.current && typeof document !== 'undefined') {
    const element = document.createElement('revo-grid');
    element.style.display = 'block';
    element.style.width = '100%';
    element.style.height = '100%';
    applyElementProperties(
      element,
      GRID_PROPERTY_NAMES,
      props,
      previousPropsRef.current,
    );
    elementRef.current = element;
  }

  useImperativeHandle(forwardedRef, () => elementRef.current, []);

  useLayoutEffect(() => {
    const element = elementRef.current;
    if (!element) {
      return;
    }
    const result = applyElementProperties(
      element,
      GRID_PROPERTY_NAMES,
      props,
      previousPropsRef.current,
      pendingSourceSyncRef.current,
    );
    if (result.sourceSyncConsumed) {
      pendingSourceSyncRef.current = null;
    }
  });

  useLayoutEffect(() => {
    const element = elementRef.current;
    if (!element) {
      return undefined;
    }
    const listeners = {};
    for (const [eventName, dashProp] of Object.entries(EVENT_MAPPINGS)) {
      listeners[eventName] = event => {
        sequenceRef.current += 1;
        const detail =
          eventName === 'afteredit'
            ? compactAfterEditDetail(event.detail)
            : event.detail;
        const envelope = createEventEnvelope(
          eventName,
          detail,
          sequenceRef.current,
        );
        const updates = { [dashProp]: envelope };
        if (
          eventName === 'afteredit' &&
          props.syncSourceOnEdit &&
          'source' in element
        ) {
          const token = createSourceSyncToken(element.source);
          pendingSourceSyncRef.current = token;
          updates.source = token.value;
        }
        if (props.setProps) {
          props.setProps(updates);
        }
      };
    }
    const genericListeners = {};
    for (const eventName of normalizeEventNames(props.eventListeners)) {
      if (eventName in EVENT_MAPPINGS) {
        continue;
      }
      genericListeners[eventName] = event => {
        sequenceRef.current += 1;
        if (props.setProps) {
          props.setProps({
            eventData: createEventEnvelope(
              eventName,
              event.detail,
              sequenceRef.current,
            ),
          });
        }
      };
    }
    const cleanupDedicated = bindEventListeners(element, listeners);
    const cleanupGeneric = bindEventListeners(element, genericListeners);
    return () => {
      cleanupDedicated();
      cleanupGeneric();
    };
  }, [
    props.eventListeners,
    props.setProps,
    props.syncSourceOnEdit,
  ]);

  useLayoutEffect(() => {
    const host = hostRef.current;
    const element = elementRef.current;
    if (!host || !element) {
      return undefined;
    }
    host.appendChild(element);
    return () => element.remove();
  }, []);

  return React.createElement('div', {
    ref: hostRef,
    id: props.id,
    className: props.className,
    style: {
      display: 'block',
      width: '100%',
      ...props.style,
    },
  });
});

RevoGrid.displayName = 'RevoGrid';

RevoGrid.propTypes = {
  /** Dash component identifier. */
  id: PropTypes.string,
  /** CSS class applied to the RevoGrid component host. */
  className: PropTypes.string,
  /** Inline style applied to the RevoGrid component host. */
  style: PropTypes.object,
  /** Enables accessibility attributes and keyboard behavior. */
  accessible: PropTypes.bool,
  /** Additional plain JSON data available to grid configuration. */
  additionalData: PropTypes.object,
  /** Applies filter changes when the filter popover closes. */
  applyOnClose: PropTypes.bool,
  /** Enables or configures automatic column sizing. */
  autoSizeColumn: PropTypes.oneOfType([PropTypes.bool, PropTypes.object]),
  /** Enables row dragging. */
  canDrag: PropTypes.bool,
  /** Allows the grid to receive focus. */
  canFocus: PropTypes.bool,
  /** Enables column reordering. */
  canMoveColumns: PropTypes.bool,
  /** Default column width in pixels. */
  colSize: PropTypes.number,
  /** Named JSON-safe column type definitions. Function members are unsupported. */
  columnTypes: PropTypes.object,
  /** Column definitions. Function-valued renderers and editors are unsupported. */
  columns: PropTypes.array,
  /** Disables horizontal virtualization. */
  disableVirtualX: PropTypes.bool,
  /** Disables vertical virtualization. */
  disableVirtualY: PropTypes.bool,
  /** Enables export behavior. */
  exporting: PropTypes.bool,
  /** Enables or configures filtering. Function-valued custom filters are unsupported. */
  filter: PropTypes.oneOfType([PropTypes.bool, PropTypes.object]),
  /** Number of extra virtualized items rendered around the viewport. */
  frameSize: PropTypes.number,
  /** JSON-safe row-grouping configuration. */
  grouping: PropTypes.object,
  /** Hides the RevoGrid attribution link. */
  hideAttribution: PropTypes.bool,
  /** Prevents wheel transfer from horizontal grid scrolling. */
  noHorizontalScrollTransfer: PropTypes.bool,
  /** Rows pinned to the bottom viewport. */
  pinnedBottomSource: PropTypes.array,
  /** Rows pinned to the top viewport. */
  pinnedTopSource: PropTypes.array,
  /** Enables range selection. */
  range: PropTypes.bool,
  /** Makes cells read-only. */
  readonly: PropTypes.bool,
  /** Enables column resizing. */
  resize: PropTypes.bool,
  /** CSS class applied to grid rows. */
  rowClass: PropTypes.string,
  /** Per-row size definitions. */
  rowDefinitions: PropTypes.array,
  /** Enables or configures row headers. */
  rowHeaders: PropTypes.oneOfType([PropTypes.bool, PropTypes.object]),
  /** Default row height in pixels. */
  rowSize: PropTypes.number,
  /** Enables right-to-left layout. */
  rtl: PropTypes.bool,
  /** JSON-safe sorting configuration. */
  sorting: PropTypes.object,
  /** Main row source. Pass DataFrame data with df.to_dict("records"). */
  source: PropTypes.array,
  /** Enables or configures column stretching. */
  stretch: PropTypes.oneOfType([PropTypes.bool, PropTypes.string]),
  /** Grid theme name. */
  theme: PropTypes.string,
  /** Map of trimmed physical row indexes. */
  trimmedRows: PropTypes.object,
  /** Enables or configures clipboard behavior. */
  useClipboard: PropTypes.oneOfType([PropTypes.bool, PropTypes.object]),
  /** Horizontal viewport dimension identifiers. */
  virtualX: PropTypes.array,
  /** Latest aftercolumnresize JSON-safe event envelope. */
  aftercolumnresize: PropTypes.object,
  /** Latest compact afteredit JSON-safe event envelope. */
  afteredit: PropTypes.object,
  /** Latest afterfocus JSON-safe event envelope. */
  afterfocus: PropTypes.object,
  /** Latest aftersortingapply JSON-safe event envelope. */
  aftersortingapply: PropTypes.object,
  /** Latest beforefilterapply notification. Python cannot cancel it synchronously. */
  beforefilterapply: PropTypes.object,
  /** Latest headerclick JSON-safe event envelope. */
  headerclick: PropTypes.object,
  /** Latest roworderchanged JSON-safe event envelope. */
  roworderchanged: PropTypes.object,
  /** Other RevoGrid event names to publish through eventData. */
  eventListeners: PropTypes.arrayOf(PropTypes.string),
  /** Latest JSON-safe event envelope from eventListeners. */
  eventData: PropTypes.object,
  /** When true, afteredit also updates the complete Dash source property. */
  syncSourceOnEdit: PropTypes.bool,
  /** Dash callback used to report property changes. */
  setProps: PropTypes.func,
};

RevoGrid.defaultProps = {
  eventListeners: [],
  syncSourceOnEdit: false,
};

export default RevoGrid;
